% ECE 538 MATLAB Homework 1

% Problem 2.65

% a) By computing crosscorrelation r_xy(l), one could easily observe the
% 	"spikes" generated by the crosscorrelation function. Each "spike"
%	corresponds to a delay that could be easily observed from the graph
%	as well. 

% b) See attached plots

% close all figures
close all

seq_len = 13;
sigma_sq = 0.01;
v = sqrt(sigma_sq) .* randn(1, 200);
D = 20;
x = [1 1 1 1 1 -1 -1 1 1 -1 1 -1 1];
x_d = [zeros(1, D) 1 1 1 1 1 -1 -1 1 1 -1 1 -1 1 zeros(1, 200 - 13 - D)];
a = 0.9;
figure(1);
plot(x);
title('13-point Barker Sequence');
xlabel('0 <= n <= 199');
ylabel('x[n]');
ylim([-1 1]);
xlim([0 199]);
y = a .* x_d + v;
figure(2);
plot(0:199, y);
title('13-point Gaussian Random Sequence \sigma^{2} = 0.01');
xlabel('0 <= n <= 199');
ylabel('y[n]');

% c) From the plot, one can tell the delay D occurs @ l = 20.

r_yx = conv(y, x(end:-1:1));
figure(3);
plot(0:59, r_yx(seq_len:seq_len + 59));
title('Crosscorrelation \sigma^{2} = 0.01');
xlabel('0 <= l <= 59');
ylabel('r_{yx}[l]');

% d) From the plots, one can still estimate the delay D occurs @ l = 20.

sigma_sq_a = 0.1;
sigma_sq_b = 1;

v = sqrt(sigma_sq_a) .* randn(1, 200);
D = 20;
y = a .* x_d + v;
figure(4);
plot(0:199, y);
title('13-point Gaussian Random Sequence \sigma^{2} = 0.1');
xlabel('0 <= n <= 199');
ylabel('y[n]');

r_yx = conv(y, x(end:-1:1));
figure(5);
plot(0:59, r_yx(seq_len:seq_len + 59));
title('Crosscorrelation \sigma^{2} = 0.1');
xlabel('0 <= l <= 59');
ylabel('r_{yx}[l]');
xlim([0 59]);

v = sqrt(sigma_sq_b) .* randn(1, 200);
D = 20;
y = a .* x_d + v;
figure(6);
plot(0:199, y);
title('13-point Gaussian Random Sequence \sigma^{2} = 1');
xlabel('0 <= n <= 199');
ylabel('y[n]');

r_yx = conv(y, x(end:-1:1));
figure(7);
plot(0:59, r_yx(seq_len:seq_len + 59));
title('Crosscorrelation \sigma^{2} = 1');
xlabel('0 <= l <= 59');
ylabel('r_{yx}[l]');
xlim([0 59]);

% e) From the plots, one can estimate the D value to remain @ l = 20.

seq_len = 15;
sigma_sq = 0.01;
v = sqrt(sigma_sq) .* randn(1, 200);
D = 20;
x = [-1 -1 -1 1 1 1 1 -1 1 -1 1 1 -1 -1 1];
x_d = [zeros(1, D) -1 -1 -1 1 1 1 1 -1 1 -1 1 1 -1 -1 1 zeros(1, 200 - 15 - D)];
a = 0.9;
figure(8);
plot(x);
title('15-point Sequence');
xlabel('0 <= n <= 199');
ylabel('x[n]');
ylim([-1 1]);
xlim([0 199]);
y = a .* x_d + v;
figure(9);
plot(0:199, y);
title('15-point Gaussian Random Sequence \sigma^{2} = 0.01');
xlabel('0 <= n <= 199');
ylabel('y[n]');

r_yx = conv(y, x(end:-1:1));
figure(10);
plot(0:59, r_yx(seq_len:seq_len + 59));
title('Crosscorrelation \sigma^{2} = 0.01');
xlabel('0 <= l <= 59');
ylabel('r_{yx}[l]');
xlim([0 59]);

v = sqrt(sigma_sq_a) .* randn(1, 200);
D = 20;
y = a .* x_d + v;
figure(11);
plot(0:199, y);
title('15-point Gaussian Random Sequence \sigma^{2} = 0.1');
xlabel('0 <= n <= 199');
ylabel('y[n]');

r_yx = conv(y, x(end:-1:1));
figure(12);
plot(0:59, r_yx(seq_len:seq_len + 59));
title('Crosscorrelation \sigma^{2} = 0.1');
xlabel('0 <= l <= 59');
ylabel('r_{yx}[l]');
xlim([0 59]);

v = sqrt(sigma_sq_b) .* randn(1, 200);
D = 20;
y = a .* x_d + v;
figure(13);
plot(0:199, y);
title('15-point Gaussian Random Sequence \sigma^{2} = 1');
xlabel('0 <= n <= 199');
ylabel('y[n]');

r_yx = conv(y, x(end:-1:1));
figure(14);
plot(0:59, r_yx(seq_len:seq_len + 59));
title('Crosscorrelation \sigma^{2} = 1');
xlabel('0 <= l <= 59');
ylabel('r_{yx}[l]');
xlim([0 59]);

% f) From the plots, one can still estimate the delay D occurs @ l = 20.

seq_len = 128;
register=[1 0 0 0 0 0 0];
for ri = 1:127,
	x(ri) = register(1, 7);
	register(2:7) = register(1:6);
	register(1, 1) = rem((register(1, 1) + x(1, ri)), 2);
end
x = 2 * x - 1;

figure(15);
plot(x);
xlim([0 199]);
title('127-point Sequence from 7-Stage Feedback Shift Register');
xlabel('0 <= n <= 199');
ylabel('x[n]');

x_d = [zeros(1, D) x(1:127) zeros(1, 200 - 127 - D)];

v = sqrt(sigma_sq) .* randn(1, 200);
v_a = sqrt(sigma_sq_a) .* randn(1, 200);
v_b = sqrt(sigma_sq_b) .* randn(1, 200);

y = a .* x_d + v;
y_a = a .* x_d + v_a;
y_b = a .* x_d + v_b;

figure(16);
plot(0:199, y);
title('127-point Gaussian Random Sequence \sigma^{2} = 0.01');
xlabel('0 <= n <= 199');
ylabel('y[n]');

r_yx = conv(y, x(end:-1:1));
figure(17);
plot(0:59, r_yx(seq_len - 1:seq_len - 1 + 59));
title('Crosscorrelation \sigma^{2} = 0.01');
xlabel('0 <= l <= 59');
ylabel('r_{yx}[l]');
xlim([0 59]);

figure(18);
plot(0:199, y_a);
title('127-point Gaussian Random Sequence \sigma^{2} = 0.1');
xlabel('0 <= n <= 199');
ylabel('y[n]');

r_yx = conv(y_a, x(end:-1:1));
figure(19);
plot(0:59, r_yx(seq_len - 1:seq_len - 1 + 59));
title('Crosscorrelation \sigma^{2} = 0.1');
xlabel('0 <= l <= 59');
ylabel('r_{yx}[l]');
xlim([0 59]);

figure(20);
plot(0:199, y_b);
title('127-point Gaussian Random Sequence \sigma^{2} = 1');
xlabel('0 <= n <= 199');
ylabel('y[n]');

r_yx = conv(y_b, x(end:-1:1));
figure(21);
plot(0:59, r_yx(seq_len - 1:seq_len - 1 + 59));
title('Crosscorrelation \sigma^{2} = 1');
xlabel('0 <= l <= 59');
ylabel('r_{yx}[l]');
xlim([0 59]);
